---
title: "101023 Statistical Learning"
author: "Mattia G."
date: '2023-10-10'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R commands notes 1

Data Structures:

- Vectors
- Matrices
- Dataframe
- Factors


```{r}
#### "colon" operator

x <- 1:10
x

seq(1,9, by = 2)

seq(8, 20, length = 6)

x <- rep(1, 10)
x <- rep(c(1, 5), 3)
y <- c(rep(2, 3), 4, 5, rep(1,5))

a <- 1:5
a

b<- 7:11

a > b
#if the len of a vector is the multiple of the other it's all good in the
# neighborhood, otherwise you have to be worried


#### "vectorised" functions

log(b)

#### some commonly used functions

x <- 22:3
length(x)
max(x)
min(x)
sum(x)
prod(x)
sort(x)

#### 3 types of variables: Numerical, Character, Logical
# character and logical vectors

y <- c("this", "is", "an", "example")
y

z <- c(5<2, 3>1, 1==0, FALSE)
z

#### conversion of elements to the same element

x <- c(TRUE, "example", 5)
x

#### R does convert all the above vector into a string
# R does convert the next vector into a numerical vector (FALSE = 0, TRUE = 1)

y <- c(TRUE, FALSE, 5)
y


#### missing values

a <- c(1, NA, 2)
st <- c("this", "is", "an", "example", NA)

a
st

#### extract elements from a vector

x<- seq(0, 20, 10)
x

x[1]
x[3]
x[1:2]
x[c(1, 3)]


x <- seq(1, 10, 2)
x

#### Beware the negative indexes, in R by indicating a negative index it
# indicates that I dont' want the element in that spec pos to be returned

x[c(-1, -4)]

#### name the elements of a vector

x <- 1:4
x

names(x)

names(x) <- c("a", "b", "c", "d")

x

names(x)

x["a"]

x[c("a", "b")]

#### use logical values to access the elements of a vector

weight <- c(80, 70, 82, 76, 90)
height <- c(170, 168, 176, 181, 180)

height[c(3, 5)]

weight.more.than.80 <- c(FALSE, FALSE, TRUE, FALSE, FALSE)
weight.more.than.80

height[weight.more.than.80]

weight.more.than.80 <-weight > 80

weight.more.than.80

height[weight > 80]


#### matrices

a <- matrix(1:6, nrow = 2)
a


b <- matrix(1:6, nrow = 2, byrow = TRUE)
b


x <- 3:8
matrix(x, ncol=2)
matrix(x, ncol=2, byrow = TRUE)

x <- c("batman", "robin", "superman", "spiderman")

matrix(x, ncol=2)
matrix(c(3>=2, 3<=5, 2==2, 1<0), nrow = 2)

#### rbind() cbind() Row/Col

a <- rbind(weight, height)
a

b <- cbind(weight, height)
b

#### dimension of a matrix

dim(a)
dim(a)[1]
dim(a)[2]
b[2][2] # b[row][column]
a[1, ] #All columns
a[, 2] #All Rows

b[1:3,2]
a[1, c(1, 4, 5)]


b[b[,1] > 80]
b[b[ ,2]> 175, ]
b[-2, ]

#### colnames and rownames

colnames(b)
rownames(b)
rownames(b)<- c("batman", "robin", "superman", "spiderman", "ironman")
rownames(b)

#### operation with matrixes

a <- matrix(0:5, nrow = 2)
b <-matrix(seq(0, 10, 2), nrow = 2)

a
b
a+b

a*b
a==5
a/b

# in R operations between matrixes are element by element but if I want do them  
# with matrix algebra:

#### matrix algebra with R

a
b <- matrix(seq(0,10,2), nrow = 3)
b
d <- a%*%b
d
#### matrix inversion

solve(d)
d%*%solve(d)

#### transpose

t(d)

#### Dataframes

weight <- c(80, 70, 82, 76, 90)
height <- c(170, 198, 176, 181, 180)
smoker <- c("yes", "yes", "no", "no", "yes")
survey <- data.frame(weight, height, smoker)

survey

survey[1:3, ]

survey[ , 2]

survey[3, ]
survey[survey[ , 3]=="yes", ]
survey[survey[ , 3]=="yes", -3]

#### the '$' operator (I need a dollar, dollar a dollar is what I need hey hey)

names(survey)
survey$weight
survey$weight[1:3]

# Every obj has attributes but there is an attribute that gets assigned by default,
# and this is "class"

#### class of an object

M <- matrix(1:9, ncol = 3)
class(M)
is.matrix(M)
is.data.frame(M)
class(survey)
is.data.frame(survey)
is.matrix(survey)

#### vectors have no specific class

a <- 1:10
is.vector(a)
is.numeric(a)
is.character(a)
class(a)

b <- c("this", "is", "a", "string")
is.vector(b)

```






